### ISSUE TITLE
在导出java程序时,多行注解并没有对应删除过滤掉

### ISSUE THREAD

**Issue by feng-siwei** [yh4922/code_copyright_gen#1]
源码
```java
/**
 * Mybatis Plus 配置
 *
 * @author fengsiwei
 */
@EnableTransactionManagement(proxyTargetClass = true)
@Configuration
public class MybatisPlusConfig {
   
```

导出后
```
/**
 * Mybatis Plus 配置
 *
 * @author fengsiwei
 */
@EnableTransactionManagement(proxyTargetClass = true)
@Configuration
public class MybatisPlusConfig {
```

**Comment by feng-siwei** [comment]
需要的话我可以提供对应源码文件
https://wwu.lanzoue.com/im4lj091akub
密码:cdgj

**Comment by yh4922** [comment]
提交了新的版本 下拉试试看
![image](https://user-images.githubusercontent.com/18353610/186840802-ffda2d91-a361-46fa-90cd-5e2ab2fa8372.png)

**Comment by shadow6336** [comment]
> 提交了新的版本 下拉试试看 ![image](https://user-images.githubusercontent.com/18353610/186840802-ffda2d91-a361-46fa-90cd-5e2ab2fa8372.png)

你这边是修改了，可是你的release那边没有修改，下拉出来的还是旧版的

**Comment by shadow6336** [comment]
> 提交了新的版本 下拉试试看 ![image](https://user-images.githubusercontent.com/18353610/186840802-ffda2d91-a361-46fa-90cd-5e2ab2fa8372.png)

大佬有时间更新一下吗
